### PR TITLE
Before applying CodeFlare manifests, check for the codeflare-operator

### LINKED ISSUE #379: Enabling distributedWorkloads before installing the Codeflare operator breaks the DSC CR
**Describe the bug**
If a user tries to enable the distributedWorkloads component before installing the Codeflare operator (e.g. on first install), the DSC CR will break and go into an error state with the following message
```
failed to reconcile distributed-workloads on DataScienceCluster : no matches for kind "InstaScale" in version "[codeflare.codeflare.dev/v1alpha1](http://codeflare.codeflare.dev/v1alpha1)"
```

**To Reproduce**
1. Install ODH
2. Create DSC CR with distributedWorkloads enabled (without installing the Codeflare operator)

**Expected behavior**
There should be a warning/info message that directs the user to installing the Codeflare operator if they want to use the component, but the DSC should not go in error state

### PR DESCRIPTION
**Pull request by etirelli**
Before applying CodeFlare manifests, check for the codeflare-operator subscription, and raise a meaningful error if not.

Fixes #379

## How Has This Been Tested?
Manually tested in the cluster. In case the codeflare operator is not installed, the following error message is raised:

```
CodeFlare operator not found in namespace openshift-operators. Please install it before enabling the codeflare component
```

## Merge criteria:
- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
Should we generalize this logic into common function that takes subscription spec inputs?  We will also need to check Subscriptions for serverless, servicemesh for kserve  and openshift-pipelines for datascience pipelines so on

File: components/codeflare/codeflare.go [hunk 1]
```diff
@@ -33,6 +42,20 @@ var _ components.ComponentInterface = (*CodeFlare)(nil)
 
 func (d *CodeFlare) ReconcileComponent(owner metav1.Object, client client.Client, scheme *runtime.Scheme, enabled bool, namespace string) error {
 
+	if enabled {
+		// check if the CodeFlare operator is installed
+		sub := &operators.Subscription{}
+		err := client.Get(context.TODO(), types.NamespacedName{Namespace: CodeflareOperatorNamespace, Name: CodeflareOperator}, sub)
```
Comment (zdtsw) [inline components/codeflare/codeflare.go:48]: is codeflare operator only possible to be installed into `openshift-operators` namespace? 
e.g user cannot choose other namespace?

Comment (zdtsw) [reply components/codeflare/codeflare.go:48]: so i checked with Anish, for ODH, it will be only openshift-operators, 
but in downstream RHODS, it might be someother namespace as well.

**Review by zdtsw — APPROVED** [review]
/lgtm

**Comment by zdtsw** [comment]
should we get this merge to "main"?
