### PR TITLE
Recreate stale OauthClient resource

### LINKED ISSUE #712: [Bug]: 500 error when trying to log in to dashboard
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

2.4.0

### Current Behavior

On a cluster that has 

There is this error in the oauth-proxy container of the rhods dashboard pods:

```
2023/11/07 14:19:35 provider.go:631: Performing OAuth discovery against https://172.30.0.1/.well-known/oauth-authorization-server
2023/11/07 14:19:35 provider.go:671: 200 GET https://172.30.0.1/.well-known/oauth-authorization-server {
"issuer": "https://oauth-openshift.apps.gcp-4-13-2-4.mzx2.s2.devshift.org/",
"authorization_endpoint": "https://oauth-openshift.apps.gcp-4-13-2-4.mzx2.s2.devshift.org/oauth/authorize",
"token_endpoint": "https://oauth-openshift.apps.gcp-4-13-2-4.mzx2.s2.devshift.org/oauth/token",
"scopes_supported": [
"user:check-access",
"user:full",
"user:info",
"user:list-projects",
"user:list-scoped-projects"
],
"response_types_supported": [
"code",
"token"
],
"grant_types_supported": [
"authorization_code",
"implicit"
],
"code_challenge_methods_supported": [
"plain",
"S256"
]
}
2023/11/07 14:19:35 oauthproxy.go:654: error redeeming code (client:10.129.2.8:52702): got 400 from "https://oauth-openshift.apps.gcp-4-13-2-4.mzx2.s2.devshift.org/oauth/token" {"error":"unauthorized_client","error_description":"The client is not authorized to request a token using this method."}
2023/11/07 14:19:35 oauthproxy.go:445: ErrorPage 500 Internal Error Internal Error
```

### Expected Behavior

It should be possible to log into the dashboard seamlessly when upgrading or installing RHODS 2.4 without any disabling/enabling process

### Steps To Reproduce

1) clean the cluster with: https://gitlab.cee.redhat.com/data-hub/olminstall/-/blob/main/cleanup.sh?ref_type=heads
2) manually remove:
2.1) [https://console-openshift-console.apps.ods-qe-03.rhods.ccitredhat.com/k8s/cluster/customresourcedefinitions[…]tions.dscinitialization.opendatahub.io](https://console-openshift-console.apps.ods-qe-03.rhods.ccitredhat.com/k8s/cluster/customresourcedefinitions/dscinitializations.dscinitialization.opendatahub.io)
2.2) [https://console-openshift-console.apps.ods-qe-03.rhods.ccitredhat.com/k8s/cluster/customresourcedefinitions[…]ters.datasciencecluster.opendatahub.io](https://console-openshift-console.apps.ods-qe-03.rhods.ccitredhat.com/k8s/cluster/customresourcedefinitions/datascienceclusters.datasciencecluster.opendatahub.io)
3) install RHODS 2.4
4) you will see that DSC Initialization is present
5) create a Data Science Cluster
you will have the error above

### Workaround (if any)

Disabling the dashboard component from the DSC and enabling it again fixed the problem

### PR DESCRIPTION
**Pull request by VaishnaviHire**
Fixes #712 
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

File: controllers/secretgenerator/secretgenerator_controller.go [hunk 1]
```diff
@@ -228,11 +228,25 @@ func (r *SecretGeneratorReconciler) createOAuthClient(ctx context.Context, name
 	if err != nil {
 		if apierrs.IsAlreadyExists(err) {
 			secGenLog.Info("OAuth client resource already exists", "name", oauthClient.Name)
-
+			existingOauthClient := &ocv1.OAuthClient{}
```
Comment (zdtsw) [inline controllers/secretgenerator/secretgenerator_controller.go:231]: guess this is for:
- check if oauth CR with Name "name" exists:
  -  yes: patch the secretName
  -  no: create it

Comment (VaishnaviHire) [reply controllers/secretgenerator/secretgenerator_controller.go:231]: We are recreating it instead of patching it.

**Review by zdtsw — APPROVED** [review]
/lgtm

based on we have the code in downstream 2.4 already

**Comment by zdtsw** [comment]
strange error  from yesterday: Account with ID 2DUeKzzTD9ngfsQ6YgkzdJn1jA4 denied access to perform create on Certificate with HTTP call POST /api/accounts_mgmt/v1/certificates"}

File: components/dashboard/dashboard.go [hunk 2]
```diff
@@ -73,7 +75,8 @@ func (d *Dashboard) GetComponentName() string {
 // Verifies that Dashboard implements ComponentInterface.
 var _ components.ComponentInterface = (*Dashboard)(nil)
 
-func (d *Dashboard) ReconcileComponent(cli client.Client, owner metav1.Object, dscispec *dsciv1.DSCInitializationSpec) error {
+//nolint:gocyclo
```
Comment (bartoszmajsak) [inline components/dashboard/dashboard.go:78]: @VaishnaviHire @zdtsw as I am merging 605 with incubation I came across this change and I am wondering what was the rationale behind disabling gocyclo linter in this particular case. 

These tools play a crucial role in ensuring our code remains straightforward and accessible, especially for those who might be revisiting it after some time or are new to the codebase.

My concern is that bypassing these checks could lead to potential challenges in maintaining the project in the long run. I'm quite curious to understand the reasoning behind explicitly disabling this check. Was there a specific obstacle that prevented simplifying the code to comply with the linter?  Maybe we can figure out together how to make this code simpler and benefit from linter complaints instead of keeping them silent? :)
